version: '3'
services:
  oracledb:
    image: aburnazy/oracle-db-xe
    environment:
      - "ORACLE_ALLOW_REMOTE=true"
#    volumes:
#      - data-oracledb:/u01/app/oracle/oradata/
    ports:
      - 49161:1521
    networks:
      - mynet
  sc:
    image: aburnazy/yota-sc
    environment:
      - "NODE_ORACLEDB_USER=yotaott"
      - "NODE_ORACLEDB_PASSWORD=yota0TT"
      - "NODE_ORACLEDB_CONNECTIONSTRING=oracledb:1521/xe"      
    depends_on: 
        - oracledb
    ports:
      - 3000:3000
    networks:
      - mynet    
  gp:
    image: aburnazy/yota-gp
    environment:
      - "NODE_ORACLEDB_USER=yotaott"
      - "NODE_ORACLEDB_PASSWORD=yota0TT"
      - "NODE_ORACLEDB_CONNECTIONSTRING=oracledb:1521/xe"    
      - "YOTA_STATUS_CHECK_HOST=sc"  
    depends_on: 
        - oracledb
    ports:
      - 3001:3001
    networks:
      - mynet
      
#volumes:
#  data-oracledb:
#    driver: local

networks:
  mynet:
    driver: bridge      