version: '3'
services:
  oracledb:
    image: dataart/oracle-db-xe
    environment:
      - "ORACLE_ALLOW_REMOTE=true"
#    volumes:
#      - data-oracledb:/u01/app/oracle/oradata/
    ports:
      - 49161:1521
    networks:
      - mynet
  cs:
    image: dataart/yota-cs
    environment:
      - "NODE_ORACLEDB_USER=yotaott"
      - "NODE_ORACLEDB_PASSWORD=yota0TT"
      - "NODE_ORACLEDB_CONNECTIONSTRING=oracledb:1521/xe"      
    depends_on: 
        - oracledb
    ports:
      - 3000:3000
    networks:
      - mynet    
  pg:
    image: dataart/yota-pg
    environment:
      - "NODE_ORACLEDB_USER=yotaott"
      - "NODE_ORACLEDB_PASSWORD=yota0TT"
      - "NODE_ORACLEDB_CONNECTIONSTRING=oracledb:1521/xe"    
      - "YOTA_STATUS_CHECK_HOST=cs"
    depends_on: 
        - oracledb
    ports:
      - 3001:3001
    networks:
      - mynet

#volumes:
#  data-oracledb:
#    driver: local

networks:
  mynet:
    driver: bridge      